### PR TITLE
Add test for edge case of Innsbruck and a test for IP-Phone numbers

### PR DESCRIPTION
**Pull request by gpoul**

### CODE REVIEW

**Comment by gpoul** [comment]
Everyone can say that but I'm pretty sure those build test errors are not from my change :)

**Comment by DrHyde** [comment]
Yeah, we can safely say that's not your fault :-)

**Comment by DrHyde** [comment]
I also added a test to make sure it extracts the right areaname() for Innsbruck.

**Comment by gpoul** [comment]
@DrHyde cool addition, thanks!

**Pull request merged**
